import { StatusBar, Platform  } from "react-native";

export const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? 44 : StatusBar.currentHeight;
export const KEY =
"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiNTYwZTQwNzE4MWJiOTY1MWE3M2NlNDVkNmVmZjI3NDVjNmNjNzEyMmJiNzBjYzljMmY1NTdjOTRkOThlYzYyZjMzMDYyYTFjYjY4ZmRkZDkiLCJpYXQiOjE2NjU3MzQ3ODUsIm5iZiI6MTY2NTczNDc4NSwiZXhwIjoxNjk3MjcwNzg1LCJzdWIiOiIxNTA1NCIsInNjb3BlcyI6W119.k3-ve_LrCzOiHa_D0HEeB4jVX8WModlCap8We48gBzmOIK_McvR2s8C97iVv6YMIVXi6dWp6_efxGeu5NHPFcg";