import { StatusBar, Platform  } from "react-native";

export const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? 44 : StatusBar.currentHeight;
export const KEY =
"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiYjI2YTkxNzY3YmUyYTYyODA2OTM1NDY2ODZmYzM1OTJhMTE3M2VlYjYzZmUxZGM1MTUzZmM5ZDg3ZWM1M2Y4NWNhZGMzNzI2MzY0ZDk4MzYiLCJpYXQiOjE2NjYzMjMwMzcsIm5iZiI6MTY2NjMyMzAzNywiZXhwIjoxNjk3ODU5MDM2LCJzdWIiOiIxNTY3NCIsInNjb3BlcyI6W119.IZcTpfwKdjb9ajvQ40gPW-LFCHWMqcKDekf0bSu1-mo_mY9N08md4rwRJtejp9Qtp76N-sqTa6zMVQZ8KgOMVQ";